### ISSUE TITLE
Adding New Element/Content Item with Preview Tab Open

### ISSUE THREAD

**Issue by lachlanhickey** [jobsta/reportbro-designer#42] opened 2020-04-14 04:44 UTC
Unsure if this is an intended feature, however when previewing a PDF report and subsequently switching back to the 'PDF Content' tab, draggable elements/content items will not add to the workspace unless the PDF preview is closed.

**Comment by alhman** [comment] 2020-04-14 11:22
I cannot reproduce this. Which browser are you using? Is there a javascript error in the console?

**Comment by lachlanhickey** [comment] 2020-04-14 11:25
Version 80.0.3987.163 (Official Build) (64-bit), Mac 10.15.3.

I replicated this issue on all of your demos. 

I just tested this on Safari, and the issue was not replicated.

**Comment by alhman** [comment] 2020-04-14 13:01
ok, so this only occurs on Chrome on MacOS. We were able to reproduce this issue and provide a fix with the next update.

**Comment by alhman** [comment] 2020-04-20 14:10
fixed in latest release 1.4.0

**Closed** 2020-04-22 14:20 UTC
