### ISSUE TITLE
Tables looses original position

### ISSUE THREAD

**Issue by Waguilar33** [jobsta/reportbro-designer#34] opened 2019-11-18 20:44 UTC
I have seen this weird behaviour where a table looses its position in the sheet. Here is a GIF showing this.

I'm saving the report in a database similar to the way python does it. After loading the report again the table looses its position.

![Nov-18-2019 14-45-47](https://user-images.githubusercontent.com/21320293/69092589-5a5db080-0a12-11ea-9bfd-4f796fa3eff4.gif)

**Comment by alhman** [comment] 2019-11-19 16:17
for me this seems like it has nothing to do with saving and loading the report but rather how the report is generated. All document elements are positioned relative to the other elements above. This means if a table grows in size (as it usually does because a table contains multiple rows) then an element below the table will also be moved down. So the margin between the table bottom and the text below stays the same.

PS: in the future it's better to report general usage questions (or when you're not sure if it's a bug) in the mailing list:
https://groups.google.com/forum/?fromgroups#!forum/reportbro

**Comment by Waguilar33** [comment] 2019-11-19 21:39
Thanks @alhman but I do think this is a bug. I have done a new report with the following objects:

- A table with a single column with a width of 50.
- A label with a yellow background.
- An image with a chosen file.
- Two line one above the other
- A table with two columns each column with a width of 100.

![Hnet-image](https://user-images.githubusercontent.com/21320293/69188502-46817f80-0ae2-11ea-9914-b3fdceb9bc00.gif)

Each object **IS NOT** bound to any parameter. Also, after several tryouts I found that the table renders correctly as long as it has at least 2 columns with a width of 100 each. This is can be seen in the second table which doesn't loose its position in the report.

**Comment by alhman** [comment] 2019-11-20 12:37
ok, now I can reproduce it. Your animated GIFs are a little bit confusing and all those extra elements are not needed. In the end it only takes a single table with a small width moved to the right side of the document. The internal position seems to be wrong and therefor will not be saved correctly. We'll have a look at this.

**Comment by Waguilar33** [comment] 2019-11-20 14:41
Cool @alhman. The intention behind the extra elements was to show that the table was the only element not saving its position.

I'm glad you were able to see the bug. Thank in advance for all your effort and help.

**Comment by alhman** [comment] 2019-12-23 15:06
fixed in v1.3.4

**Closed by alhman** 2019-12-23 15:06 UTC
