### ISSUE TITLE
Safari allows Nested Arrays/Map Due to Failed Object Comparison

### ISSUE THREAD

**Issue by michaelwoodard** [jobsta/reportbro-designer#30] opened 2019-10-22 18:04 UTC
There is a line of code that is failing with Safari, but executes fine within Chrome/Firefox. It is a comparison of the the parent item and the current parameter item.

`// do not allow nested array/map
        if (obj.getPanelItem() !== null && obj.getPanelItem().getParent() === this.rb.getMainPanel().getParametersItem()) {
            $('#rbro_parameter_type option[value="array"]').removeClass('rbroHidden');
            $('#rbro_parameter_type option[value="map"]').removeClass('rbroHidden');
        } else {
            $('#rbro_parameter_type option[value="array"]').addClass('rbroHidden');
            $('#rbro_parameter_type option[value="map"]').addClass('rbroHidden');
        }`

The failure is within the obj.getPanelItem().getParent() === this.rb.getMainPanel().getParametersItem(). Returns false in Chrome/Firefox, but true in Safari. This allowed me to build a pretty complex parameter setup that I was hoping it would work.

Looks like it needs to be implemented another way. I do have to ask is there a reason it won't work with highly complexed javascript.

**Comment by alhman** [comment] 2019-11-04 10:17
The comparison works fine, the problem is that Safari does not support hiding select options via css. This will be fixed with the next update.

**Comment by alhman** [comment] 2019-11-08 14:29
fixed in latest version 1.3.3

**Closed by alhman** 2019-11-08 14:29 UTC
